-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 18:14:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema andaman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema andaman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `andaman` DEFAULT CHARACTER SET utf8 ;
USE `andaman` ;

-- -----------------------------------------------------
-- Table `andaman`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `broker_order_id` INT UNSIGNED NOT NULL,
  `trade_configuration_id` INT UNSIGNED NOT NULL,
  `units` FLOAT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL,
  `profit` FLOAT NOT NULL,
  `time_at_open` BIGINT UNSIGNED NOT NULL,
  `price_at_open` FLOAT NOT NULL,
  `time_at_close` BIGINT UNSIGNED NULL DEFAULT NULL,
  `price_at_close` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_algorithm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_algorithm` (
  `trade_algorithm_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` SMALLINT UNSIGNED NOT NULL,
  `param_hash` VARCHAR(64) NOT NULL,
  `param` TEXT NOT NULL,
  `trade_direction` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_algorithm_id`),
  UNIQUE INDEX `trade_type_UNIQUE` (`type` ASC) VISIBLE,
  UNIQUE INDEX `trade_param_UNIQUE` (`param_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_set` (
  `trade_set_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL,
  `created_at` BIGINT UNSIGNED NOT NULL,
  `updated_at` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_set_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_configuration` (
  `trade_configuration_id` INT NOT NULL AUTO_INCREMENT,
  `trade_pair` TINYINT UNSIGNED NOT NULL,
  `timezone` TINYINT UNSIGNED NOT NULL,
  `trade_algorithm_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_configuration_id`),
  UNIQUE INDEX `trade_pair_UNIQUE` (`trade_pair` ASC) VISIBLE,
  UNIQUE INDEX `timezone_UNIQUE` (`timezone` ASC) VISIBLE,
  UNIQUE INDEX `trade_algorithm_id_UNIQUE` (`trade_algorithm_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_set_configuration_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_set_configuration_rel` (
  `trade_set_id` INT NOT NULL,
  `trade_configuration_id` INT NOT NULL,
  PRIMARY KEY (`trade_set_id`, `trade_configuration_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
