-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 10:46:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema andaman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema andaman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `andaman` DEFAULT CHARACTER SET utf8 ;
USE `andaman` ;

-- -----------------------------------------------------
-- Table `andaman`.`trade_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_run_id` INT UNSIGNED NOT NULL,
  `broker_order_id` INT UNSIGNED NOT NULL,
  `trade_configuration_id` INT UNSIGNED NOT NULL,
  `units` FLOAT UNSIGNED NOT NULL,
  `trade_direction` TINYINT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL,
  `profit` FLOAT NOT NULL,
  `time_at_open` BIGINT UNSIGNED NOT NULL,
  `price_at_open` FLOAT NOT NULL,
  `time_at_close` BIGINT UNSIGNED NOT NULL,
  `price_at_close` FLOAT NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `RUN_ORDER` (`trade_run_id` ASC, `broker_order_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_algorithm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_algorithm` (
  `trade_algorithm_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` SMALLINT UNSIGNED NOT NULL,
  `param_hash` VARCHAR(64) NOT NULL,
  `param` TEXT NOT NULL,
  `trade_direction` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_algorithm_id`),
  UNIQUE INDEX `type_param_hash` (`type` ASC, `param_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_set` (
  `trade_set_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `created_at` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_set_id`),
  UNIQUE INDEX `UNIQUE` (`name` ASC, `version` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_configuration` (
  `trade_configuration_id` INT NOT NULL AUTO_INCREMENT,
  `trade_pair` TINYINT UNSIGNED NOT NULL,
  `timezone` TINYINT UNSIGNED NOT NULL,
  `trade_algorithm_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_configuration_id`),
  UNIQUE INDEX `fields` (`trade_pair` ASC, `timezone` ASC, `trade_algorithm_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_set_configuration_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_set_configuration_rel` (
  `trade_set_id` INT NOT NULL,
  `trade_configuration_id` INT NOT NULL,
  PRIMARY KEY (`trade_set_id`, `trade_configuration_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andaman`.`trade_run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andaman`.`trade_run` (
  `trade_run_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_set_id` INT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL,
  `created_at` BIGINT UNSIGNED NOT NULL,
  `start_at` BIGINT UNSIGNED NOT NULL,
  `finish_at` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`trade_run_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
